/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppAccountingIndexRouteImport } from './routes/_app/accounting/index'
import { Route as AppAiIndexRouteImport } from './routes/_app/ai/index'
import { Route as AppAttendanceIndexRouteImport } from './routes/_app/attendance/index'
import { Route as AppHrIndexRouteImport } from './routes/_app/hr/index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory/index'
import { Route as AppPartnersIndexRouteImport } from './routes/_app/partners/index'
import { Route as AppPartnersIdRouteImport } from './routes/_app/partners/$id'
import { Route as AppPayrollIndexRouteImport } from './routes/_app/payroll/index'
import { Route as AppPurchaseIndexRouteImport } from './routes/_app/purchase/index'
import { Route as AppSalesIndexRouteImport } from './routes/_app/sales/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppAccountingAccountsIndexRouteImport } from './routes/_app/accounting/accounts/index'
import { Route as AppAccountingBillsIndexRouteImport } from './routes/_app/accounting/bills/index'
import { Route as AppAccountingInvoicesIndexRouteImport } from './routes/_app/accounting/invoices/index'
import { Route as AppAccountingMovesIdRouteImport } from './routes/_app/accounting/moves/$id'
import { Route as AppAiChatIndexRouteImport } from './routes/_app/ai/chat/index'
import { Route as AppAiDocumentsIndexRouteImport } from './routes/_app/ai/documents/index'
import { Route as AppAttendanceRecordsIndexRouteImport } from './routes/_app/attendance/records/index'
import { Route as AppHrEmployeesIndexRouteImport } from './routes/_app/hr/employees/index'
import { Route as AppHrEmployeesIdRouteImport } from './routes/_app/hr/employees/$id'
import { Route as AppInventoryAttributesIndexRouteImport } from './routes/_app/inventory/attributes/index'
import { Route as AppInventoryLotsIndexRouteImport } from './routes/_app/inventory/lots/index'
import { Route as AppInventoryProductsIndexRouteImport } from './routes/_app/inventory/products/index'
import { Route as AppInventoryProductsIdRouteImport } from './routes/_app/inventory/products/$id'
import { Route as AppInventoryProductsNewRouteImport } from './routes/_app/inventory/products/new'
import { Route as AppInventoryStockIndexRouteImport } from './routes/_app/inventory/stock/index'
import { Route as AppInventoryTransfersIndexRouteImport } from './routes/_app/inventory/transfers/index'
import { Route as AppInventoryTransfersIdRouteImport } from './routes/_app/inventory/transfers/$id'
import { Route as AppInventoryTransfersNewRouteImport } from './routes/_app/inventory/transfers/new'
import { Route as AppInventoryWarehousesIndexRouteImport } from './routes/_app/inventory/warehouses/index'
import { Route as AppPayrollPayslipsIdRouteImport } from './routes/_app/payroll/payslips/$id'
import { Route as AppPayrollRunsIndexRouteImport } from './routes/_app/payroll/runs/index'
import { Route as AppPayrollRunsIdRouteImport } from './routes/_app/payroll/runs/$id'
import { Route as AppPurchaseOrdersIndexRouteImport } from './routes/_app/purchase/orders/index'
import { Route as AppPurchaseOrdersIdRouteImport } from './routes/_app/purchase/orders/$id'
import { Route as AppSalesOrdersIndexRouteImport } from './routes/_app/sales/orders/index'
import { Route as AppSalesOrdersIdRouteImport } from './routes/_app/sales/orders/$id'
import { Route as AppSettingsApiKeysIndexRouteImport } from './routes/_app/settings/api-keys/index'
import { Route as AppSettingsCompanyIndexRouteImport } from './routes/_app/settings/company/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingIndexRoute = AppAccountingIndexRouteImport.update({
  id: '/accounting/',
  path: '/accounting/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiIndexRoute = AppAiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceIndexRoute = AppAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => AppRoute,
} as any)
const AppHrIndexRoute = AppHrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppPartnersIndexRoute = AppPartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersIdRoute = AppPartnersIdRouteImport.update({
  id: '/partners/$id',
  path: '/partners/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollIndexRoute = AppPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseIndexRoute = AppPurchaseIndexRouteImport.update({
  id: '/purchase/',
  path: '/purchase/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingAccountsIndexRoute =
  AppAccountingAccountsIndexRouteImport.update({
    id: '/accounting/accounts/',
    path: '/accounting/accounts/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAccountingBillsIndexRoute = AppAccountingBillsIndexRouteImport.update({
  id: '/accounting/bills/',
  path: '/accounting/bills/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingInvoicesIndexRoute =
  AppAccountingInvoicesIndexRouteImport.update({
    id: '/accounting/invoices/',
    path: '/accounting/invoices/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAccountingMovesIdRoute = AppAccountingMovesIdRouteImport.update({
  id: '/accounting/moves/$id',
  path: '/accounting/moves/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAiChatIndexRoute = AppAiChatIndexRouteImport.update({
  id: '/ai/chat/',
  path: '/ai/chat/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiDocumentsIndexRoute = AppAiDocumentsIndexRouteImport.update({
  id: '/ai/documents/',
  path: '/ai/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRecordsIndexRoute =
  AppAttendanceRecordsIndexRouteImport.update({
    id: '/attendance/records/',
    path: '/attendance/records/',
    getParentRoute: () => AppRoute,
  } as any)
const AppHrEmployeesIndexRoute = AppHrEmployeesIndexRouteImport.update({
  id: '/hr/employees/',
  path: '/hr/employees/',
  getParentRoute: () => AppRoute,
} as any)
const AppHrEmployeesIdRoute = AppHrEmployeesIdRouteImport.update({
  id: '/hr/employees/$id',
  path: '/hr/employees/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryAttributesIndexRoute =
  AppInventoryAttributesIndexRouteImport.update({
    id: '/attributes/',
    path: '/attributes/',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryLotsIndexRoute = AppInventoryLotsIndexRouteImport.update({
  id: '/lots/',
  path: '/lots/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryProductsIndexRoute =
  AppInventoryProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryProductsIdRoute = AppInventoryProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryProductsNewRoute = AppInventoryProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryStockIndexRoute = AppInventoryStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryTransfersIndexRoute =
  AppInventoryTransfersIndexRouteImport.update({
    id: '/transfers/',
    path: '/transfers/',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryTransfersIdRoute = AppInventoryTransfersIdRouteImport.update({
  id: '/transfers/$id',
  path: '/transfers/$id',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryTransfersNewRoute =
  AppInventoryTransfersNewRouteImport.update({
    id: '/transfers/new',
    path: '/transfers/new',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryWarehousesIndexRoute =
  AppInventoryWarehousesIndexRouteImport.update({
    id: '/warehouses/',
    path: '/warehouses/',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppPayrollPayslipsIdRoute = AppPayrollPayslipsIdRouteImport.update({
  id: '/payroll/payslips/$id',
  path: '/payroll/payslips/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRunsIndexRoute = AppPayrollRunsIndexRouteImport.update({
  id: '/payroll/runs/',
  path: '/payroll/runs/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRunsIdRoute = AppPayrollRunsIdRouteImport.update({
  id: '/payroll/runs/$id',
  path: '/payroll/runs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersIndexRoute = AppPurchaseOrdersIndexRouteImport.update({
  id: '/purchase/orders/',
  path: '/purchase/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersIdRoute = AppPurchaseOrdersIdRouteImport.update({
  id: '/purchase/orders/$id',
  path: '/purchase/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOrdersIndexRoute = AppSalesOrdersIndexRouteImport.update({
  id: '/sales/orders/',
  path: '/sales/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOrdersIdRoute = AppSalesOrdersIdRouteImport.update({
  id: '/sales/orders/$id',
  path: '/sales/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsApiKeysIndexRoute = AppSettingsApiKeysIndexRouteImport.update({
  id: '/settings/api-keys/',
  path: '/settings/api-keys/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCompanyIndexRoute = AppSettingsCompanyIndexRouteImport.update({
  id: '/settings/company/',
  path: '/settings/company/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/partners/$id': typeof AppPartnersIdRoute
  '/accounting/': typeof AppAccountingIndexRoute
  '/ai/': typeof AppAiIndexRoute
  '/attendance/': typeof AppAttendanceIndexRoute
  '/hr/': typeof AppHrIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/partners/': typeof AppPartnersIndexRoute
  '/payroll/': typeof AppPayrollIndexRoute
  '/purchase/': typeof AppPurchaseIndexRoute
  '/sales/': typeof AppSalesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/accounting/moves/$id': typeof AppAccountingMovesIdRoute
  '/hr/employees/$id': typeof AppHrEmployeesIdRoute
  '/inventory/products/$id': typeof AppInventoryProductsIdRoute
  '/inventory/products/new': typeof AppInventoryProductsNewRoute
  '/inventory/transfers/$id': typeof AppInventoryTransfersIdRoute
  '/inventory/transfers/new': typeof AppInventoryTransfersNewRoute
  '/payroll/payslips/$id': typeof AppPayrollPayslipsIdRoute
  '/payroll/runs/$id': typeof AppPayrollRunsIdRoute
  '/purchase/orders/$id': typeof AppPurchaseOrdersIdRoute
  '/sales/orders/$id': typeof AppSalesOrdersIdRoute
  '/accounting/accounts/': typeof AppAccountingAccountsIndexRoute
  '/accounting/bills/': typeof AppAccountingBillsIndexRoute
  '/accounting/invoices/': typeof AppAccountingInvoicesIndexRoute
  '/ai/chat/': typeof AppAiChatIndexRoute
  '/ai/documents/': typeof AppAiDocumentsIndexRoute
  '/attendance/records/': typeof AppAttendanceRecordsIndexRoute
  '/hr/employees/': typeof AppHrEmployeesIndexRoute
  '/inventory/attributes/': typeof AppInventoryAttributesIndexRoute
  '/inventory/lots/': typeof AppInventoryLotsIndexRoute
  '/inventory/products/': typeof AppInventoryProductsIndexRoute
  '/inventory/stock/': typeof AppInventoryStockIndexRoute
  '/inventory/transfers/': typeof AppInventoryTransfersIndexRoute
  '/inventory/warehouses/': typeof AppInventoryWarehousesIndexRoute
  '/payroll/runs/': typeof AppPayrollRunsIndexRoute
  '/purchase/orders/': typeof AppPurchaseOrdersIndexRoute
  '/sales/orders/': typeof AppSalesOrdersIndexRoute
  '/settings/api-keys/': typeof AppSettingsApiKeysIndexRoute
  '/settings/company/': typeof AppSettingsCompanyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/partners/$id': typeof AppPartnersIdRoute
  '/accounting': typeof AppAccountingIndexRoute
  '/ai': typeof AppAiIndexRoute
  '/attendance': typeof AppAttendanceIndexRoute
  '/hr': typeof AppHrIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/partners': typeof AppPartnersIndexRoute
  '/payroll': typeof AppPayrollIndexRoute
  '/purchase': typeof AppPurchaseIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/accounting/moves/$id': typeof AppAccountingMovesIdRoute
  '/hr/employees/$id': typeof AppHrEmployeesIdRoute
  '/inventory/products/$id': typeof AppInventoryProductsIdRoute
  '/inventory/products/new': typeof AppInventoryProductsNewRoute
  '/inventory/transfers/$id': typeof AppInventoryTransfersIdRoute
  '/inventory/transfers/new': typeof AppInventoryTransfersNewRoute
  '/payroll/payslips/$id': typeof AppPayrollPayslipsIdRoute
  '/payroll/runs/$id': typeof AppPayrollRunsIdRoute
  '/purchase/orders/$id': typeof AppPurchaseOrdersIdRoute
  '/sales/orders/$id': typeof AppSalesOrdersIdRoute
  '/accounting/accounts': typeof AppAccountingAccountsIndexRoute
  '/accounting/bills': typeof AppAccountingBillsIndexRoute
  '/accounting/invoices': typeof AppAccountingInvoicesIndexRoute
  '/ai/chat': typeof AppAiChatIndexRoute
  '/ai/documents': typeof AppAiDocumentsIndexRoute
  '/attendance/records': typeof AppAttendanceRecordsIndexRoute
  '/hr/employees': typeof AppHrEmployeesIndexRoute
  '/inventory/attributes': typeof AppInventoryAttributesIndexRoute
  '/inventory/lots': typeof AppInventoryLotsIndexRoute
  '/inventory/products': typeof AppInventoryProductsIndexRoute
  '/inventory/stock': typeof AppInventoryStockIndexRoute
  '/inventory/transfers': typeof AppInventoryTransfersIndexRoute
  '/inventory/warehouses': typeof AppInventoryWarehousesIndexRoute
  '/payroll/runs': typeof AppPayrollRunsIndexRoute
  '/purchase/orders': typeof AppPurchaseOrdersIndexRoute
  '/sales/orders': typeof AppSalesOrdersIndexRoute
  '/settings/api-keys': typeof AppSettingsApiKeysIndexRoute
  '/settings/company': typeof AppSettingsCompanyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/partners/$id': typeof AppPartnersIdRoute
  '/_app/accounting/': typeof AppAccountingIndexRoute
  '/_app/ai/': typeof AppAiIndexRoute
  '/_app/attendance/': typeof AppAttendanceIndexRoute
  '/_app/hr/': typeof AppHrIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/partners/': typeof AppPartnersIndexRoute
  '/_app/payroll/': typeof AppPayrollIndexRoute
  '/_app/purchase/': typeof AppPurchaseIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/accounting/moves/$id': typeof AppAccountingMovesIdRoute
  '/_app/hr/employees/$id': typeof AppHrEmployeesIdRoute
  '/_app/inventory/products/$id': typeof AppInventoryProductsIdRoute
  '/_app/inventory/products/new': typeof AppInventoryProductsNewRoute
  '/_app/inventory/transfers/$id': typeof AppInventoryTransfersIdRoute
  '/_app/inventory/transfers/new': typeof AppInventoryTransfersNewRoute
  '/_app/payroll/payslips/$id': typeof AppPayrollPayslipsIdRoute
  '/_app/payroll/runs/$id': typeof AppPayrollRunsIdRoute
  '/_app/purchase/orders/$id': typeof AppPurchaseOrdersIdRoute
  '/_app/sales/orders/$id': typeof AppSalesOrdersIdRoute
  '/_app/accounting/accounts/': typeof AppAccountingAccountsIndexRoute
  '/_app/accounting/bills/': typeof AppAccountingBillsIndexRoute
  '/_app/accounting/invoices/': typeof AppAccountingInvoicesIndexRoute
  '/_app/ai/chat/': typeof AppAiChatIndexRoute
  '/_app/ai/documents/': typeof AppAiDocumentsIndexRoute
  '/_app/attendance/records/': typeof AppAttendanceRecordsIndexRoute
  '/_app/hr/employees/': typeof AppHrEmployeesIndexRoute
  '/_app/inventory/attributes/': typeof AppInventoryAttributesIndexRoute
  '/_app/inventory/lots/': typeof AppInventoryLotsIndexRoute
  '/_app/inventory/products/': typeof AppInventoryProductsIndexRoute
  '/_app/inventory/stock/': typeof AppInventoryStockIndexRoute
  '/_app/inventory/transfers/': typeof AppInventoryTransfersIndexRoute
  '/_app/inventory/warehouses/': typeof AppInventoryWarehousesIndexRoute
  '/_app/payroll/runs/': typeof AppPayrollRunsIndexRoute
  '/_app/purchase/orders/': typeof AppPurchaseOrdersIndexRoute
  '/_app/sales/orders/': typeof AppSalesOrdersIndexRoute
  '/_app/settings/api-keys/': typeof AppSettingsApiKeysIndexRoute
  '/_app/settings/company/': typeof AppSettingsCompanyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/mfa'
    | '/reset-password'
    | '/inventory'
    | '/partners/$id'
    | '/accounting/'
    | '/ai/'
    | '/attendance/'
    | '/hr/'
    | '/inventory/'
    | '/partners/'
    | '/payroll/'
    | '/purchase/'
    | '/sales/'
    | '/settings/'
    | '/accounting/moves/$id'
    | '/hr/employees/$id'
    | '/inventory/products/$id'
    | '/inventory/products/new'
    | '/inventory/transfers/$id'
    | '/inventory/transfers/new'
    | '/payroll/payslips/$id'
    | '/payroll/runs/$id'
    | '/purchase/orders/$id'
    | '/sales/orders/$id'
    | '/accounting/accounts/'
    | '/accounting/bills/'
    | '/accounting/invoices/'
    | '/ai/chat/'
    | '/ai/documents/'
    | '/attendance/records/'
    | '/hr/employees/'
    | '/inventory/attributes/'
    | '/inventory/lots/'
    | '/inventory/products/'
    | '/inventory/stock/'
    | '/inventory/transfers/'
    | '/inventory/warehouses/'
    | '/payroll/runs/'
    | '/purchase/orders/'
    | '/sales/orders/'
    | '/settings/api-keys/'
    | '/settings/company/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/mfa'
    | '/reset-password'
    | '/partners/$id'
    | '/accounting'
    | '/ai'
    | '/attendance'
    | '/hr'
    | '/inventory'
    | '/partners'
    | '/payroll'
    | '/purchase'
    | '/sales'
    | '/settings'
    | '/accounting/moves/$id'
    | '/hr/employees/$id'
    | '/inventory/products/$id'
    | '/inventory/products/new'
    | '/inventory/transfers/$id'
    | '/inventory/transfers/new'
    | '/payroll/payslips/$id'
    | '/payroll/runs/$id'
    | '/purchase/orders/$id'
    | '/sales/orders/$id'
    | '/accounting/accounts'
    | '/accounting/bills'
    | '/accounting/invoices'
    | '/ai/chat'
    | '/ai/documents'
    | '/attendance/records'
    | '/hr/employees'
    | '/inventory/attributes'
    | '/inventory/lots'
    | '/inventory/products'
    | '/inventory/stock'
    | '/inventory/transfers'
    | '/inventory/warehouses'
    | '/payroll/runs'
    | '/purchase/orders'
    | '/sales/orders'
    | '/settings/api-keys'
    | '/settings/company'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/mfa'
    | '/reset-password'
    | '/_app/inventory'
    | '/_app/partners/$id'
    | '/_app/accounting/'
    | '/_app/ai/'
    | '/_app/attendance/'
    | '/_app/hr/'
    | '/_app/inventory/'
    | '/_app/partners/'
    | '/_app/payroll/'
    | '/_app/purchase/'
    | '/_app/sales/'
    | '/_app/settings/'
    | '/_app/accounting/moves/$id'
    | '/_app/hr/employees/$id'
    | '/_app/inventory/products/$id'
    | '/_app/inventory/products/new'
    | '/_app/inventory/transfers/$id'
    | '/_app/inventory/transfers/new'
    | '/_app/payroll/payslips/$id'
    | '/_app/payroll/runs/$id'
    | '/_app/purchase/orders/$id'
    | '/_app/sales/orders/$id'
    | '/_app/accounting/accounts/'
    | '/_app/accounting/bills/'
    | '/_app/accounting/invoices/'
    | '/_app/ai/chat/'
    | '/_app/ai/documents/'
    | '/_app/attendance/records/'
    | '/_app/hr/employees/'
    | '/_app/inventory/attributes/'
    | '/_app/inventory/lots/'
    | '/_app/inventory/products/'
    | '/_app/inventory/stock/'
    | '/_app/inventory/transfers/'
    | '/_app/inventory/warehouses/'
    | '/_app/payroll/runs/'
    | '/_app/purchase/orders/'
    | '/_app/sales/orders/'
    | '/_app/settings/api-keys/'
    | '/_app/settings/company/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  MfaRoute: typeof MfaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/': {
      id: '/_app/accounting/'
      path: '/accounting'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AppAccountingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/': {
      id: '/_app/ai/'
      path: '/ai'
      fullPath: '/ai/'
      preLoaderRoute: typeof AppAiIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance/': {
      id: '/_app/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AppAttendanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/': {
      id: '/_app/hr/'
      path: '/hr'
      fullPath: '/hr/'
      preLoaderRoute: typeof AppHrIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/partners/': {
      id: '/_app/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof AppPartnersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners/$id': {
      id: '/_app/partners/$id'
      path: '/partners/$id'
      fullPath: '/partners/$id'
      preLoaderRoute: typeof AppPartnersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/': {
      id: '/_app/payroll/'
      path: '/payroll'
      fullPath: '/payroll/'
      preLoaderRoute: typeof AppPayrollIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase/': {
      id: '/_app/purchase/'
      path: '/purchase'
      fullPath: '/purchase/'
      preLoaderRoute: typeof AppPurchaseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/accounts/': {
      id: '/_app/accounting/accounts/'
      path: '/accounting/accounts'
      fullPath: '/accounting/accounts/'
      preLoaderRoute: typeof AppAccountingAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/bills/': {
      id: '/_app/accounting/bills/'
      path: '/accounting/bills'
      fullPath: '/accounting/bills/'
      preLoaderRoute: typeof AppAccountingBillsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/invoices/': {
      id: '/_app/accounting/invoices/'
      path: '/accounting/invoices'
      fullPath: '/accounting/invoices/'
      preLoaderRoute: typeof AppAccountingInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/moves/$id': {
      id: '/_app/accounting/moves/$id'
      path: '/accounting/moves/$id'
      fullPath: '/accounting/moves/$id'
      preLoaderRoute: typeof AppAccountingMovesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/chat/': {
      id: '/_app/ai/chat/'
      path: '/ai/chat'
      fullPath: '/ai/chat/'
      preLoaderRoute: typeof AppAiChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/documents/': {
      id: '/_app/ai/documents/'
      path: '/ai/documents'
      fullPath: '/ai/documents/'
      preLoaderRoute: typeof AppAiDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance/records/': {
      id: '/_app/attendance/records/'
      path: '/attendance/records'
      fullPath: '/attendance/records/'
      preLoaderRoute: typeof AppAttendanceRecordsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/employees/': {
      id: '/_app/hr/employees/'
      path: '/hr/employees'
      fullPath: '/hr/employees/'
      preLoaderRoute: typeof AppHrEmployeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/employees/$id': {
      id: '/_app/hr/employees/$id'
      path: '/hr/employees/$id'
      fullPath: '/hr/employees/$id'
      preLoaderRoute: typeof AppHrEmployeesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/attributes/': {
      id: '/_app/inventory/attributes/'
      path: '/attributes'
      fullPath: '/inventory/attributes/'
      preLoaderRoute: typeof AppInventoryAttributesIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/lots/': {
      id: '/_app/inventory/lots/'
      path: '/lots'
      fullPath: '/inventory/lots/'
      preLoaderRoute: typeof AppInventoryLotsIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/products/': {
      id: '/_app/inventory/products/'
      path: '/products'
      fullPath: '/inventory/products/'
      preLoaderRoute: typeof AppInventoryProductsIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/products/$id': {
      id: '/_app/inventory/products/$id'
      path: '/products/$id'
      fullPath: '/inventory/products/$id'
      preLoaderRoute: typeof AppInventoryProductsIdRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/products/new': {
      id: '/_app/inventory/products/new'
      path: '/products/new'
      fullPath: '/inventory/products/new'
      preLoaderRoute: typeof AppInventoryProductsNewRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/stock/': {
      id: '/_app/inventory/stock/'
      path: '/stock'
      fullPath: '/inventory/stock/'
      preLoaderRoute: typeof AppInventoryStockIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/transfers/': {
      id: '/_app/inventory/transfers/'
      path: '/transfers'
      fullPath: '/inventory/transfers/'
      preLoaderRoute: typeof AppInventoryTransfersIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/transfers/$id': {
      id: '/_app/inventory/transfers/$id'
      path: '/transfers/$id'
      fullPath: '/inventory/transfers/$id'
      preLoaderRoute: typeof AppInventoryTransfersIdRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/transfers/new': {
      id: '/_app/inventory/transfers/new'
      path: '/transfers/new'
      fullPath: '/inventory/transfers/new'
      preLoaderRoute: typeof AppInventoryTransfersNewRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/warehouses/': {
      id: '/_app/inventory/warehouses/'
      path: '/warehouses'
      fullPath: '/inventory/warehouses/'
      preLoaderRoute: typeof AppInventoryWarehousesIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/payroll/payslips/$id': {
      id: '/_app/payroll/payslips/$id'
      path: '/payroll/payslips/$id'
      fullPath: '/payroll/payslips/$id'
      preLoaderRoute: typeof AppPayrollPayslipsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/runs/': {
      id: '/_app/payroll/runs/'
      path: '/payroll/runs'
      fullPath: '/payroll/runs/'
      preLoaderRoute: typeof AppPayrollRunsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/runs/$id': {
      id: '/_app/payroll/runs/$id'
      path: '/payroll/runs/$id'
      fullPath: '/payroll/runs/$id'
      preLoaderRoute: typeof AppPayrollRunsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase/orders/': {
      id: '/_app/purchase/orders/'
      path: '/purchase/orders'
      fullPath: '/purchase/orders/'
      preLoaderRoute: typeof AppPurchaseOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase/orders/$id': {
      id: '/_app/purchase/orders/$id'
      path: '/purchase/orders/$id'
      fullPath: '/purchase/orders/$id'
      preLoaderRoute: typeof AppPurchaseOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/orders/': {
      id: '/_app/sales/orders/'
      path: '/sales/orders'
      fullPath: '/sales/orders/'
      preLoaderRoute: typeof AppSalesOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/orders/$id': {
      id: '/_app/sales/orders/$id'
      path: '/sales/orders/$id'
      fullPath: '/sales/orders/$id'
      preLoaderRoute: typeof AppSalesOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/api-keys/': {
      id: '/_app/settings/api-keys/'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys/'
      preLoaderRoute: typeof AppSettingsApiKeysIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/company/': {
      id: '/_app/settings/company/'
      path: '/settings/company'
      fullPath: '/settings/company/'
      preLoaderRoute: typeof AppSettingsCompanyIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppInventoryRouteChildren {
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppInventoryProductsIdRoute: typeof AppInventoryProductsIdRoute
  AppInventoryProductsNewRoute: typeof AppInventoryProductsNewRoute
  AppInventoryTransfersIdRoute: typeof AppInventoryTransfersIdRoute
  AppInventoryTransfersNewRoute: typeof AppInventoryTransfersNewRoute
  AppInventoryAttributesIndexRoute: typeof AppInventoryAttributesIndexRoute
  AppInventoryLotsIndexRoute: typeof AppInventoryLotsIndexRoute
  AppInventoryProductsIndexRoute: typeof AppInventoryProductsIndexRoute
  AppInventoryStockIndexRoute: typeof AppInventoryStockIndexRoute
  AppInventoryTransfersIndexRoute: typeof AppInventoryTransfersIndexRoute
  AppInventoryWarehousesIndexRoute: typeof AppInventoryWarehousesIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppInventoryProductsIdRoute: AppInventoryProductsIdRoute,
  AppInventoryProductsNewRoute: AppInventoryProductsNewRoute,
  AppInventoryTransfersIdRoute: AppInventoryTransfersIdRoute,
  AppInventoryTransfersNewRoute: AppInventoryTransfersNewRoute,
  AppInventoryAttributesIndexRoute: AppInventoryAttributesIndexRoute,
  AppInventoryLotsIndexRoute: AppInventoryLotsIndexRoute,
  AppInventoryProductsIndexRoute: AppInventoryProductsIndexRoute,
  AppInventoryStockIndexRoute: AppInventoryStockIndexRoute,
  AppInventoryTransfersIndexRoute: AppInventoryTransfersIndexRoute,
  AppInventoryWarehousesIndexRoute: AppInventoryWarehousesIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppRouteChildren {
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppPartnersIdRoute: typeof AppPartnersIdRoute
  AppAccountingIndexRoute: typeof AppAccountingIndexRoute
  AppAiIndexRoute: typeof AppAiIndexRoute
  AppAttendanceIndexRoute: typeof AppAttendanceIndexRoute
  AppHrIndexRoute: typeof AppHrIndexRoute
  AppPartnersIndexRoute: typeof AppPartnersIndexRoute
  AppPayrollIndexRoute: typeof AppPayrollIndexRoute
  AppPurchaseIndexRoute: typeof AppPurchaseIndexRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppAccountingMovesIdRoute: typeof AppAccountingMovesIdRoute
  AppHrEmployeesIdRoute: typeof AppHrEmployeesIdRoute
  AppPayrollPayslipsIdRoute: typeof AppPayrollPayslipsIdRoute
  AppPayrollRunsIdRoute: typeof AppPayrollRunsIdRoute
  AppPurchaseOrdersIdRoute: typeof AppPurchaseOrdersIdRoute
  AppSalesOrdersIdRoute: typeof AppSalesOrdersIdRoute
  AppAccountingAccountsIndexRoute: typeof AppAccountingAccountsIndexRoute
  AppAccountingBillsIndexRoute: typeof AppAccountingBillsIndexRoute
  AppAccountingInvoicesIndexRoute: typeof AppAccountingInvoicesIndexRoute
  AppAiChatIndexRoute: typeof AppAiChatIndexRoute
  AppAiDocumentsIndexRoute: typeof AppAiDocumentsIndexRoute
  AppAttendanceRecordsIndexRoute: typeof AppAttendanceRecordsIndexRoute
  AppHrEmployeesIndexRoute: typeof AppHrEmployeesIndexRoute
  AppPayrollRunsIndexRoute: typeof AppPayrollRunsIndexRoute
  AppPurchaseOrdersIndexRoute: typeof AppPurchaseOrdersIndexRoute
  AppSalesOrdersIndexRoute: typeof AppSalesOrdersIndexRoute
  AppSettingsApiKeysIndexRoute: typeof AppSettingsApiKeysIndexRoute
  AppSettingsCompanyIndexRoute: typeof AppSettingsCompanyIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppPartnersIdRoute: AppPartnersIdRoute,
  AppAccountingIndexRoute: AppAccountingIndexRoute,
  AppAiIndexRoute: AppAiIndexRoute,
  AppAttendanceIndexRoute: AppAttendanceIndexRoute,
  AppHrIndexRoute: AppHrIndexRoute,
  AppPartnersIndexRoute: AppPartnersIndexRoute,
  AppPayrollIndexRoute: AppPayrollIndexRoute,
  AppPurchaseIndexRoute: AppPurchaseIndexRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppAccountingMovesIdRoute: AppAccountingMovesIdRoute,
  AppHrEmployeesIdRoute: AppHrEmployeesIdRoute,
  AppPayrollPayslipsIdRoute: AppPayrollPayslipsIdRoute,
  AppPayrollRunsIdRoute: AppPayrollRunsIdRoute,
  AppPurchaseOrdersIdRoute: AppPurchaseOrdersIdRoute,
  AppSalesOrdersIdRoute: AppSalesOrdersIdRoute,
  AppAccountingAccountsIndexRoute: AppAccountingAccountsIndexRoute,
  AppAccountingBillsIndexRoute: AppAccountingBillsIndexRoute,
  AppAccountingInvoicesIndexRoute: AppAccountingInvoicesIndexRoute,
  AppAiChatIndexRoute: AppAiChatIndexRoute,
  AppAiDocumentsIndexRoute: AppAiDocumentsIndexRoute,
  AppAttendanceRecordsIndexRoute: AppAttendanceRecordsIndexRoute,
  AppHrEmployeesIndexRoute: AppHrEmployeesIndexRoute,
  AppPayrollRunsIndexRoute: AppPayrollRunsIndexRoute,
  AppPurchaseOrdersIndexRoute: AppPurchaseOrdersIndexRoute,
  AppSalesOrdersIndexRoute: AppSalesOrdersIndexRoute,
  AppSettingsApiKeysIndexRoute: AppSettingsApiKeysIndexRoute,
  AppSettingsCompanyIndexRoute: AppSettingsCompanyIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  MfaRoute: MfaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
